debug

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -42,6 +42,15 @@ jobs:
         with:
           main-branch-name: ${{ github.base_ref }}
 
+      - name: Set up secret file
+        env:
+          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+        run: |
+          echo $NPM_TOKEN >> secrets.txt
+
+        - name: Run tmate
+          uses: mxschmitt/action-tmate@v2
+
       - name: Setup Node.js
         uses: ./.github/actions/node-step
         with:
@@ -53,14 +62,21 @@ jobs:
         with:
           name: npm-log
           path: /home/runner/.npm/_logs/
-          
+      
+      # Only display the NPM log if the node-step action fails.
       - name: Display NPM Log
+        if: failure() 
         run: |
           # Find the most recent log file
           LOG_FILE=$(ls -t /home/runner/.npm/_logs/ | head -n 1)
           # Display the contents of the log file
           cat /home/runner/.npm/_logs/$LOG_FILE
         shell: bash
+      
+      # Fail the workflow if any of the previous steps fail.
+      - name: Fail Action
+        if: failure()
+        run: exit 1
 
       - name: Cache npm dependencies
         uses: actions/cache@v4
@@ -96,36 +112,10 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Set up secret file
-        env:
-          DEBUG_PASSWORD: ${{ secrets.DEBUG_PASSWORD }}
-          DEBUG_SECRET_KEY: ${{ secrets.DEBUG_SECRET_KEY }}
-        run: |
-          echo $DEBUG_PASSWORD >> secrets.txt
-          echo $DEBUG_SECRET_KEY >> secrets.txt
-
-      - name: Run tmate
-        uses: mxschmitt/action-tmate@v2
-
       # Continue even if the action fails so we can display the NPM log.
       - name: Setup Node.js
         uses: ./.github/actions/node-step
         continue-on-error: true 
-
-      # Only display the NPM log if the node-step action fails.
-      - name: Display NPM Log
-        if: failure() 
-        run: |
-          # Find the most recent log file
-          LOG_FILE=$(ls -t /home/runner/.npm/_logs/ | head -n 1)
-          # Display the contents of the log file
-          cat /home/runner/.npm/_logs/$LOG_FILE
-        shell: bash
-      
-      # Fail the workflow if any of the previous steps fail.
-      - name: Fail Action
-        if: failure()
-        run: exit 1
 
       - name: Cache Playwright browsers
         uses: actions/cache@v4
